language: ruby
services:
  - redis-server
bundler_args: --without staging,production
rvm:
- 2.1.2
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- cp config/database.travis.yml config/database.yml
- cp .env.example .env
install:
  rvm @global do gem uninstall bundler -x && gem install bundler -v '~> 1.7' && bundle install
script:
- bundle install
- bundle exec rake db:drop:all
- bundle exec rake db:create:all
- bundle exec rake db:schema:load
- bundle exec rake --trace
